#joint trajectory controller and Cartesian controller
arm_controller:
  # joint trajectory controller
  type: velocity_controllers/JointTrajectoryController
  topic: "test"
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint
  gains:
    arm_1_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_2_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_3_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_4_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_5_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_6_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    arm_7_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.5
      arm_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_3_joint: {trajectory: 0.1, goal: 0.1}
      arm_4_joint: {trajectory: 0.1, goal: 0.1}
      arm_5_joint: {trajectory: 0.1, goal: 0.1}
      arm_6_joint: {trajectory: 0.1, goal: 0.1}
      arm_7_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

  #all
  joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

  ## trajectory controller parameters
  #ptp_vel: 1.5 # rad/sec
  #ptp_acc: 0.2 # rad/sec^2
  #max_error: 0.25 # rad
  #overlap_time: 0.4
  #frequency: 68
  #operation_mode: velocity

  # twist controller parameters
  base_link: arm_base_link
  tip_link: arm_7_link

  # frame_tracker + interactive_marker
  active_frame: arm_7_link
  tracking_frame: arm_7_target
  root_frame: world
  movable_trans: true
  movable_rot: true
  pid_trans: {p: 10000.0, i: 1.507, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  update_rate: 68.0
  max_vel_lin: 10.0
  max_vel_rot: 6.28

  ##position controller
  #arm_1_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_1_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_2_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_2_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_3_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_3_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_4_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_4_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_5_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_5_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_6_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_6_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  #arm_7_joint_position_controller:
    #type: velocity_controllers/JointPositionController
    #joint: arm_7_joint
    #pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}


  #velocity controller
  arm_1_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_1_joint
  arm_2_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_2_joint
  arm_3_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_3_joint
  arm_4_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_4_joint
  arm_5_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_5_joint
  arm_6_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_6_joint
  arm_7_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_7_joint
